# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT
CONFIG_ZMK_SLEEP=n

# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# 5 profiles (n+2)
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

# display
CONFIG_ZMK_DISPLAY=y
CONFIG_BT_BAS=n
#CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y
